[fmt]
line_length = 100
single_line_statement_blocks = "single"
sort_imports = true

[profile.default]
optimizer = true
optimizer_runs = 20_000
remappings = ['forge-std/=lib/forge-std/src/']

[profile.ethereum]
solc_version = "0.8.25"

[profile.zksync]
solc_version = "0.8.24"
